spring:
  application:
    name: customer-service
  mongodb:
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
    username: root
    password: root123

server:
  port: 8090
