spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
      username: root
      password: root123
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecom.notification.kafka.order.OrderConfirmation, paymentConfirmation:com.ecom.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: root
    password: root123
    properties:
      mail:
        smtp:
          trust: '*'     
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040  