spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ecom.kafka.producer.OrderConfirmationNotification
        
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-payment-group
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecom.kafka.producer.OrderPaymentSuccess
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    payment-url: http://localhost:8222/api/v1/payment
    product-url: http://localhost:8222/api/v1/product/purchase
    product-find-url: http://localhost:8222/api/v1/product/findById